name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . -t my-flask-app

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: integrationdep.azurecr.io
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Push Image to Azure Container Registry
      run: |
        docker tag my-flask-app integrationdep.azurecr.io/my-flask-app:v1
        docker push integrationdep.azurecr.io/my-flask-app:v1
